### ISSUE TITLE
Throwing Client Error on Firefox / Older browsers

### ISSUE THREAD

**Issue by theobiabo** [RedWilly/Pump-UI#23]
![image](https://github.com/user-attachments/assets/6642839e-5cb1-4b85-aae8-98b59d52137c)

**Comment by RedWilly** [comment]
my is working -  i dont see such message

**Comment by theobiabo** [comment]
ok awesome, maybe it just an edge case to be checked, thanks for feedback and sorry for the late reply ser 🤗🤗

**Comment by RedWilly** [comment]
yeah, you should try accessing the page again
